language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"

go_import_path: github.com/maxgodfrey2004/mines

install:
  - go get -t ./...
  - go get github.com/nsf/termbox-go

script: 
  - go build -v -o main.exe main.go
